apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: cGFzc3dvcmRfbWFuYWdlcl9kYg==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: czNjcmV0IQ==
  MYSQL_ROOT_PASSWORD: dG9vcg==