name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 using Temurin distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Correct distribution name

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Set up Docker Buildx for multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:latest

      # Step 6: Set up SonarQube scanner
      - name: Set up SonarQube scanner
        uses: sonarsource/sonarcloud-github-action@master
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}  # Secret token from SonarQube
          sonar-project-key: "Microservice-Based-Password-Manager-with-a-Secure-CI-CD-Pipeline"  # Your project key
          sonar-project-name: "Microservice-Based-Password-Manager"  # Your project name
          sonar.host.url: ${{ secrets.SONAR_HOST_URL }}  # SonarQube server URL from secrets

      # Step 7: Check Docker Compose version (optional check for Compose functionality)
      - name: Check out Docker Compose version
        run: docker compose --version

      # Step 8: Build and run Docker Compose to set up the environment
      - name: Build and run Docker Compose
        env:
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          docker compose up -d
